a=(1,2,3,4,5)
# print(type(a))
# print(len(a))
# print(a.count(2))
# print(a.index(2))
# print( 2 in a)
# print(sorted(a))
print(max(a))
print(sum(a))
print(a*2)
print(id(a))
print(id(a))
# t1=(1,2,3)
# t2=(4,5,6)
# print(t1+t2)